#!/bin/bash
# Script: generate_class_chart.sh
# Purpose: Generate dynamic class charts (UML diagrams) for CppBoilerplate using Doxygen and Graphviz
# Usage: ./scripts/generate_class_chart.sh

set -e

SCRIPTDIR="$(cd -- "$(dirname "$0")" >/dev/null 2>&1; pwd -P)"
PROJECT_ROOT="$(dirname "$SCRIPTDIR")"
cd "$PROJECT_ROOT"

DOXYFILE="Doxyfile"

# Check for Doxygen
if ! command -v doxygen &> /dev/null; then
    echo "[ERROR] Doxygen is not installed. Please install it: sudo apt-get install doxygen"
    exit 1
fi

# Check for Graphviz
if ! command -v dot &> /dev/null; then
    echo "[ERROR] Graphviz is not installed. Please install it: sudo apt-get install graphviz"
    exit 1
fi

# Generate default Doxyfile if not present
if [ ! -f "$DOXYFILE" ]; then
    echo "[INFO] No Doxyfile found. Generating default configuration..."
    doxygen -g "$DOXYFILE"
fi

# Update Doxyfile for project specifics
sed -i 's|^INPUT *=.*|INPUT = include src|' "$DOXYFILE"
sed -i 's|^RECURSIVE *=.*|RECURSIVE = YES|' "$DOXYFILE"
sed -i 's|^EXTRACT_ALL *=.*|EXTRACT_ALL = YES|' "$DOXYFILE"
sed -i 's|^GENERATE_HTML *=.*|GENERATE_HTML = YES|' "$DOXYFILE"
sed -i 's|^GENERATE_LATEX *=.*|GENERATE_LATEX = NO|' "$DOXYFILE"
sed -i 's|^HAVE_DOT *=.*|HAVE_DOT = YES|' "$DOXYFILE"
sed -i 's|^CALL_GRAPH *=.*|CALL_GRAPH = YES|' "$DOXYFILE"
sed -i 's|^CLASS_DIAGRAMS *=.*|CLASS_DIAGRAMS = YES|' "$DOXYFILE"
sed -i 's|^DOT_IMAGE_FORMAT *=.*|DOT_IMAGE_FORMAT = svg|' "$DOXYFILE"
if grep -q '^HTML_OUTPUT' "$DOXYFILE"; then
    sed -i 's|^HTML_OUTPUT *=.*|HTML_OUTPUT = docs|' "$DOXYFILE"
else
    echo 'HTML_OUTPUT = docs' >> "$DOXYFILE"
fi

# Run Doxygen
echo "[INFO] Running Doxygen to generate documentation and class charts..."
doxygen "$DOXYFILE"

HTML_DIR="$(grep '^HTML_OUTPUT' "$DOXYFILE" | awk '{print $3}')"
if [ -z "$HTML_DIR" ]; then
    HTML_DIR="docs"
fi

DIAGRAM_PAGE="$PROJECT_ROOT/$HTML_DIR/hierarchy.html"

echo "[SUCCESS] Class charts generated. Open $PROJECT_ROOT/$HTML_DIR/index.html in your browser to view UML diagrams."
echo "[SUCCESS] Class charts generated."
echo "[INFO] Main documentation: $PROJECT_ROOT/$HTML_DIR/index.html"
echo "[INFO] Direct class diagram (UML): $DIAGRAM_PAGE"

# Inject/Update UML diagram link in index.html
INDEX_HTML="$PROJECT_ROOT/$HTML_DIR/index.html"
if [ -f "$INDEX_HTML" ]; then
    # Remove any previous injected UML link
    sed -i '/<div style="margin:2em 0;">/,/<\/div>/d' "$INDEX_HTML"
    # Insert after <div class="contents"> (use single quotes for sed portability)
    sed -i '/<div class="contents">/a \
<div style="margin:2em 0;">\n  <h2>📊 <a href="hierarchy.html">View Dynamic Class Diagram (UML)</a></h2>\n  <p>Click above to see the current class hierarchy and relationships, generated by Doxygen & Graphviz.</p>\n</div>' "$INDEX_HTML"
    echo "[INFO] UML diagram link injected into index.html."
else
    echo "[WARN] index.html not found, could not inject UML diagram link."
fi
